name: TheIBroadcast
version: '${version}'
main: theigoro.theibroadcast.TheIBroadcast
api-version: 1.19
description: Plugin de aviso (broadcast) desenvolvido pelo TheIgoro.


commands:
  bc:
  reloadbc: